name: Build and test bwpy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install 7zip
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install p7zip-full p7zip-rar
    - name: Download example data
      run: |
        wget https://resources.3brain.com/f1/downloads/DataSet_05_Slice_3Sec.7z -O sample.7z
        7z e sample.7z -y
        mv DataSet_05_Slice_3sec.brw tests/test_samples/sample.brw
        ls tests/test_samples
    - name: Install dependencies & self
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt --prefer-binary
        pip install -e .
    - name: Run tests & coverage
      run: |
        coverage run -m unittest discover -v -s ./tests
        bash <(curl -s https://codecov.io/bash)
