name: docs

on: [push]

jobs:
  check-documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install pip
        pip install -r docs/requirements.txt
        pip install sphinx
        pip install -e .
    - name: Build documentations and fail on warnings
      run: cd docs && sphinx-build -nW -b html source build/html
